# Generated by Django 3.0.4 on 2020-06-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='user_ID',
            field=models.CharField(max_length=100),
        ),
    ]
