# Generated by Django 3.0.4 on 2020-06-20 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth0login', '0002_auto_20200620_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
