# Generated by Django 3.0.4 on 2020-06-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth0login', '0003_delete_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('doctorName', models.CharField(max_length=100)),
                ('prevReport', models.FileField(upload_to='uploadsReport/')),
                ('prevScans', models.FileField(upload_to='uploadsScans/')),
                ('status', models.BooleanField(default=False)),
                ('medicines', models.CharField(blank=True, max_length=250)),
                ('tests', models.CharField(blank=True, max_length=250)),
                ('summery', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
